function dN=diff_shape_Q9(ksi,eta);

    dN=[-(ksi/2 - 1/4)*(- eta^2 + eta), -(2*eta - 1)*(- ksi^2/4 + ksi/4);...
        -(ksi/2 + 1/4)*(- eta^2 + eta),    (2*eta - 1)*(ksi^2/4 + ksi/4);...
           (ksi/2 + 1/4)*(eta^2 + eta),    (2*eta + 1)*(ksi^2/4 + ksi/4);...
           (ksi/2 - 1/4)*(eta^2 + eta), -(2*eta + 1)*(- ksi^2/4 + ksi/4);...
                   ksi*(- eta^2 + eta),     -(2*eta - 1)*(ksi^2/2 - 1/2);...
              -(eta^2 - 1)*(ksi + 1/2),         -2*eta*(ksi^2/2 + ksi/2);...
                    -ksi*(eta^2 + eta),     -(2*eta + 1)*(ksi^2/2 - 1/2);...
              -(eta^2 - 1)*(ksi - 1/2),        2*eta*(- ksi^2/2 + ksi/2);...
                    2*ksi*(eta^2 - 1),                2*eta*(ksi^2 - 1)];
end
